---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mock; fi
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - py.test --cov=./letmein ./tests
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls

